security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: bcrypt
    providers:
        #users_in_memory: { memory: null }
        users_in_database:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #provider: users_in_memory
            user_checker: App\Security\UserChecker
            
            lazy: true
            provider: users_in_database
            form_login:
                login_path: login
                check_path: login
                default_target_path: Home
            logout:
                path: logout
                target: Home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800  # 1 week in seconds
                path:     /
                # always_remember_me and remember_me_parameter are optional
                always_remember_me: false
                remember_me_parameter: '_remember_me'
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin , roles: ROLE_ADMIN }
        - { path: ^/offre , roles: ROLE_ADMIN }
        - { path: ^/coursE, roles: ROLE_TEACHER }
        - { path: ^/cours, roles: [ROLE_STUDENT, ROLE_TEACHER] }
        - { path: ^/offre, roles: ROLE_ENTREPRISE }
        - { path: ^/list, roles: ROLE_STUDENT }
        - { path: ^/profile, roles: [ROLE_ADMIN, ROLE_CLUB, ROLE_STUDENT, ROLE_TEACHER, ROLE_ENTREPRISE] }


