#index:
#    path: /
#    controller: App\Controller\DefaultController::index
candidature_show:
    path: /candidature/{id}
    controller: App\Controller\CandidatureController::show
    methods: GET

app_offre_list:
    path: /list
    controller: App\Controller\OffreController::list
    methods: [GET, POST]

app_accepter_candidature:
    path: /candidature/{id}/accepter
    controller: App\Controller\CandidatureController::accepterCandidature

app_refuser_candidature:
    path: /candidature/{id}/refuser
    controller: App\Controller\CandidatureController::refuserCandidature
    methods: ['POST']

download_pdf:
    path: /download-pdf/{id}
    controller: App\Controller\CandidatureController::downloadPdf