app_inscription_new:
    path: /inscrire/new/{id_activite}
    controller: 'App\Controller\ActivitesController\InscrireController::new'
    methods: ['GET', 'POST']

checkout_payment:
    path: /checkout/payment
    controller: App\Controller\ActivitesController\CheckoutController::payment



